### ISSUE TITLE
Support NAT Traversal

### ISSUE THREAD

**Issue by vthapar** [stolostron/submariner-addon#102]
* What would you like to be added:
Support enable/disable [NAT Traversal ](https://submariner.io/operations/nat-traversal/) feature of Submariner

* Why is this needed:
NAT Traversal is always enabled. Submariner supports option to disable but this option is missing in submariner-addon.

**Comment by nyechiel** [comment]
@vthapar the IPsec NATT is already customizable AFAICT. We are only missing the option to disable NAT as tracked here https://github.com/open-cluster-management/submariner-addon/issues/82 - unless I am missing anything?

**Comment by vthapar** [comment]
@nyechiel Yes, I raised the issue before investigating what parts of NATT are supported and what not. @sridhargaddam also mentioned that we may need to support option to set the natt-discovery-port, looking into that too.

**Comment by nyechiel** [comment]
@sridhargaddam @vthapar what's the status of this one?
