### ISSUE TITLE
Perform auto uninstall-add-on when cluster is deleted

### ISSUE THREAD

**Issue by sridhargaddam** [stolostron/submariner-addon#131]
When a cluster that is part of the clusterset is deleted without invoking "Uninstall add-on", we should internally cleanup the necessary endpoints from the hub cluster broker namespace. Otherwise, stale endpoints show up on the member clusters.

**Comment by nyechiel** [comment]
@sridhargaddam just making sure that this is still in your radar for 2.5. Probably the last remaining item in the uninstall work.

**Comment by sridhargaddam** [comment]
@tpantelis did you get a chance to look at this use-case?

**Comment by tpantelis** [comment]
> @nyechiel I'll have to syncup with @tpantelis to see if he was looking into this issue.

I haven't specifically but, from the summary, it seems like this should be part of the broader ACM product, ie if a `ManagedCluster` is being deleted, it should ensure all associated `ManageClusterAddon`s etc are properly deleted/cleaned up rather than putting this responsibility on each addon.

**Comment by sridhargaddam** [comment]
Thanks @tpantelis. @nyechiel Ideally the user is expected to uninstall the add-on which will trigger the Submariner un-installation properly. So, this issue is more like an edge case which still needs to be handled. But, it requires proper design and implementation. IMHO in the given timeline, it would be hard to achieve it for 2.5

**Comment by nyechiel** [comment]
> Thanks @tpantelis. @nyechiel Ideally the user is expected to uninstall the add-on which will trigger the Submariner un-installation properly. So, this issue is more like an edge case which still needs to be handled. But, it requires proper design and implementation. IMHO in the given timeline, it would be hard to achieve it for 2.5

Thanks. Is there anything else that needs to be done for the basic uninstall flow from ACM? If so, do we have it tracked separately?

**Comment by sridhargaddam** [comment]
> Thanks. Is there anything else that needs to be done for the basic uninstall flow from ACM? If so, do we have it tracked separately?

I did some basic testing from ACM UI and the regular uninstall flow was working fine. I'm not aware of anything else that needs to be handled. CC: @tpantelis

**Comment by skitt** [comment]
Migrated to https://issues.redhat.com/browse/ACM-3129.
