### ISSUE TITLE
Updating the images in ClusterServiceVersion is not restarting the pods

### ISSUE THREAD

**Issue by sridhargaddam** [stolostron/submariner-addon#189]
Following the [readme](https://github.com/open-cluster-management/submariner-addon#test-with-acm), I modified the submariner-addon image by updating the ClusterServiceVersion. However, the submariner-addon pods in the open-cluster-management namespaces are not restarted and the corresponding deployment is not updated as well.

Manually updating the submariner-addon deployment in open-cluster-management namespace fixed the issue.

**Comment by maayanf24** [comment]
@sridhargaddam  - if this still relevant, please open an issue to track in Jira

**Comment by sridhargaddam** [comment]
> @sridhargaddam - if this still relevant, please open an issue to track in Jira

Will check with the latest deployments and update/raise-issue-accordingly.

**Comment by sridhargaddam** [comment]
I verified this in ACM 2.7.1 release and was not able to reproduce the issue. When I modified the submariner-addon image in the CSV to some invalid image, I could see that submariner-addon pod got restarted in the open-cluster-management namespace and it was in InvalidImageName (as expected).

![Screenshot from 2023-03-11 01-10-22](https://user-images.githubusercontent.com/6574656/224412638-0eaf6bdc-857d-4603-8b5b-0c0f2356b997.png)
