### ISSUE TITLE
Move AWS cloud preparation to the spoke

### ISSUE THREAD

**Issue by tpantelis** [stolostron/submariner-addon#218]
GCP cloud preparation is done in the spoke so, for consistency, simplicity, and maintainability, we should perform all cloud preparation in the spoke. This would make the controllers platform agnostic and put all platform decision logic in the cloud provider factory.

**Comment by cmwylie19** [comment]
initial investigation:
- Are there any issues moving this (AWS) to the spoke?

**Comment by nyechiel** [comment]
@skitt @tpantelis while still doable, I wonder if it's not too late/risky for 2.7. Wdyt?

**Comment by skitt** [comment]
I agree, it’s too late for this. We can move it to 2.8.

**Comment by tpantelis** [comment]
> @skitt @tpantelis while still doable, I wonder if it's not too late/risky for 2.7. Wdyt?

I think it's risky no matter what release it goes into 😄 It looks like code freeze is Dec 29th but with the holidays it's about 3 weeks including testing in a real AWS env (which I'd need some help/guidance with).

**Comment by nyechiel** [comment]
> > @skitt @tpantelis while still doable, I wonder if it's not too late/risky for 2.7. Wdyt?
> 
> I think it's risky no matter what release it goes into smile It looks like code freeze is Dec 29th but with the holidays it's about 3 weeks including testing in a real AWS env (which I'd need some help/guidance with).

Let's move out from 2.7 for now. We can revisit for 2.8.
