### ISSUE TITLE
Allow custom name for `submarinerConfig`

### ISSUE THREAD

**Issue by Jaanki** [stolostron/submariner-addon#221]
Currently submarinerConfig needs to be named `submariner`. Allow for a custom name to be specified. Also make submarinerConfig controller log more verbose.

**Comment by maayanf24** [comment]
@Jaanki  - if this still relevant, please open an issue to track in Jira

**Comment by skitt** [comment]
There doesn’t seem to be a use-case for this. A lot of the addon assumes that the `SubmarinerConfig` is named `submariner`.
