### ISSUE TITLE
Add InstallPlan variable to SubmarinerConfig

### ISSUE THREAD

**Issue by manosnoam** [stolostron/submariner-addon#270]
In order to pin Submariner operator version installed, to prevent auto update with its default Subscription:
https://github.com/stolostron/submariner-addon/blob/e9fb85939918d4b1e52d007e192827a05c061c87/pkg/hub/submarineragent/manifests/operator/submariner-operator-subscription.yaml#L10

Please add installPlanApproval variable to SubmarinerConfig, so it can be set to "Manual".

**Comment by skitt** [comment]
> According to the [submarinerconfig](https://github.com/stolostron/submariner-addon/blob/main/deploy/config/crds/submarineraddon.open-cluster-management.io_submarinerconfigs.yaml#L103-L120) object, `installPlan` parameter is not supported within the `SubmarinerConfig`.

I think that’s the point of this feature request — to add some way of configuring `installPlanApproval` in `SubmarinerConfig`.

**Comment by nyechiel** [comment]
@skitt IIUC, this would also need to be backported to release-2.4 once merged?

@sridhargaddam @tpantelis can you review please? This is currently blocking QE downstream.

**Comment by skitt** [comment]
> @skitt IIUC, this would also need to be backported to release-2.4 once merged?

Yes, I’ve queued a cherry-pick.
