### ISSUE TITLE
Upgrade the addon to Submariner 0.12.0-rc0

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#304]
This involves a number of changes.

- [x] Upgrade the dependencies in `go.mod` and deal with the fallout.
- [x] Ensure that 0.12.0-rc0 images are available in the appropriate repository.
- [x] Change the default deployed version in `pkg/hub/submarineragent/manifests/operator/submariner.io-submariners-cr.yaml`.
- [x] Change the deployed version in `scripts/deploy.sh`.

**Comment by Jaanki** [comment]
Updated deploy script to use subm v0.12.0-rc0 in https://github.com/stolostron/submariner-addon/pull/307

**Comment by Jaanki** [comment]
0.12.0-rc0 images are available in quay.io/submariner as well.
