### ISSUE TITLE
Document the ClusterRole privileges in the threat model

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#326]
#325, if/when merged, will grant the Submariner addon permissions to create, delete and get ClusterRoles, which should be justified in the threat model.

**Comment by nyechiel** [comment]
@skitt I think this one was done as well?

**Comment by skitt** [comment]
> @skitt I think this one was done as well?

The justification specifically for #325 hasn’t been added to the threat model, I’ll take care of it.
