### ISSUE TITLE
Add OVN support

### ISSUE THREAD

**Issue by vthapar** [stolostron/submariner-addon#388]
When using OVNKubernetes as CNI we don't need to open all the vxlan ports in the cloud. So only open the vxlan ports required based on which CNI is used during cloud prepare step.

1. Detect if OVNKubernetes is the CNI
2. If yes, open the minimal set of ports.

**Comment by nyechiel** [comment]
@vthapar @skitt are we planning to do anything here anytime soon? should we close this one or move back to the backlog?

**Comment by nyechiel** [comment]
Based on 2.7 planning discussion this is nice to have. @vthapar to explore if we can get it done for 2.7

**Comment by nyechiel** [comment]
@skitt we need to track this in Jira going forward and close this issue.

**Comment by skitt** [comment]
Migrated to https://issues.redhat.com/browse/ACM-2844.
