### ISSUE TITLE
CRDs and CSVs should be checked during the build

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#395]
`make verify-scripts` should check that regenerating the CRDs (`make update-crds`) and the CSV (`make update-csv`) doesn’t result in any change.

CRDs are already supposed to be verified using `hack/verify-crds.sh`, but it doesn’t compare the content of the CRDs with their theoretical content. A similar script should be written for the CSV.

**Comment by dfarrell07** [comment]
I can work on this, but I don't know if I can get to it this (short) week.

**Comment by dfarrell07** [comment]
This was implemented in https://github.com/stolostron/submariner-addon/pull/507 and https://github.com/stolostron/submariner-addon/pull/508, but probably @skitt should review to make sure they meet the requirements before I close this.

**Comment by skitt** [comment]
This needs #521; see #519 and #520 for the verification PRs.

**Comment by nyechiel** [comment]
@dfarrell07 @skitt what's the latest with this one? Should we move it over to Jira or just close it?

**Comment by skitt** [comment]
Migrated to https://issues.redhat.com/browse/ACM-4006
