### ISSUE TITLE
gcp: Gateway nodes not labelled due to resource limits

### ISSUE THREAD

**Issue by vthapar** [stolostron/submariner-addon#405]
Installing OCP 4.10 with ACM 2.5.1 on GCP failed on one of the clusters with error Gateway Nodes not labelled.

```
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  creationTimestamp: "2022-06-22T08:41:18Z"
  finalizers:
  - submarineraddon.open-cluster-management.io/config-cleanup
  generation: 2
  name: submariner
  namespace: blue
  resourceVersion: "101685"
  uid: 8d8db683-912c-4447-857b-63c1c14d6ba3
spec:
  IPSecIKEPort: 500
  IPSecNATTPort: 4500
  NATTDiscoveryPort: 4900
  NATTEnable: true
  cableDriver: vxlan
  credentialsSecret:
    name: blue-gcp-creds
  gatewayConfig:
    aws:
      instanceType: m5n.large
    gateways: 1
  imagePullSpecs: {}
  loadBalancerEnable: false
  subscriptionConfig:
    source: redhat-operators
    sourceNamespace: openshift-marketplace
status:
  conditions:
  - lastTransitionTime: "2022-06-22T08:41:24Z"
    message: SubmarinerConfig was applied
    reason: SubmarinerConfigApplied
    status: "True"
    type: SubmarinerConfigApplied
  - lastTransitionTime: "2022-06-22T08:41:31Z"
    message: Submariner cluster environment was prepared
    reason: SubmarinerClusterEnvPrepared
    status: "True"
    type: SubmarinerClusterEnvironmentPrepared
  - lastTransitionTime: "2022-06-22T08:41:31Z"
    message: The 0 worker nodes labeled as gateways ("") does not match the desired
      number 1
    reason: InsufficientNodes
    status: "False"
    type: SubmarinerGatewaysLabeled
  managedClusterInfo:
    clusterName: blue
    infraId: vthapar-blue-vr7gj
    platform: GCP
    region: us-east1
    vendor: OpenShift
```
UPDATE: This was due to resource quote limit issues, but it was not clear enough from logs. There is nothing to fix but improve the logging and error message. Instead of telling user "gw not labelled" it would be better to give error message "Failed to create gw nodes" alongwith relevant resource limit error msg string.

**Comment by vthapar** [comment]
[testday-0.13.0-gcp-4.10-acm.zip](https://github.com/stolostron/submariner-addon/files/8956171/testday-0.13.0-gcp-4.10-acm.zip)

**Comment by nyechiel** [comment]
This seems to be a resource quota issue and not an actual bug. The question is can we improve the logs to give us a better hint? @aswinsuryan any thoughts on this?

**Comment by manosnoam** [comment]
See slack thread about GCP quota limit:
https://coreos.slack.com/archives/CSZLMKPS5/p1655974790531529

**Comment by aswinsuryan** [comment]
@nyechiel we need to check the machine set status to see if we can provide a more relevant reason.

**Comment by nyechiel** [comment]
@vthapar @aswinsuryan this sound like a nice to have enhancement to me. I am not sure if we have bandwitdh to handle this for 2.6, so moving to the backlog for now. Do you agree?

**Comment by nyechiel** [comment]
Also @vthapar - it seems like I can't edit the title of this issue. Can you please change it to something more generic?

**Comment by aswinsuryan** [comment]
> @vthapar @aswinsuryan this sound like a nice to have enhancement to me. I am not sure if we have bandwitdh to handle this for 2.6, so moving to the backlog for now. Do you agree?

yes this is more a enhancement and this needs to be done for all the cloud providers when we are doing it.
