### ISSUE TITLE
Drop vendoring

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#450]
The addon repository stores its `vendor` directory, but with `go.sum` and caching this doesn’t present any benefits, and it causes issues in some circumstances (downstream caching with Cachito for example).

We should remove the `vendor` directory and change the build infrastructure to suit.

**Comment by dfarrell07** [comment]
See discussion: https://coreos.slack.com/archives/C01TNQYSZQQ/p1658282019933879

**Comment by Jaanki** [comment]
PR: https://github.com/stolostron/submariner-addon/pull/515

**Comment by nyechiel** [comment]
@Jaanki can this be moved to done?
