### ISSUE TITLE
Define resource limits in the CSV

### ISSUE THREAD

**Issue by skitt** [stolostron/submariner-addon#472]
As requested in https://issues.redhat.com/browse/MTSRE-640, we should define resource limits (for memory; see also https://home.robusta.dev/blog/stop-using-cpu-limits/). Once a sensible memory limit is determined, it should be specified in `deploy/config/operator/operator.yaml` and the CSV updated (`make update-csv`).

**Comment by skitt** [comment]
@Jaanki for this one, we need to run Submariner on a full-blown ACM test setup, see what the memory usage is, and then add corresponding memory limits to the YAML file.

**Comment by nyechiel** [comment]
@Jaanki are you looking at this?

**Comment by Jaanki** [comment]
@nyechiel Yes.

**Comment by Jaanki** [comment]
PR: https://github.com/stolostron/submariner-addon/pull/654
