### ISSUE TITLE
Update subm-operator to accommodate changes done after operator-sdk upgrade

### ISSUE THREAD

**Issue by Jaanki** [stolostron/submariner-addon#481]
operator-sdk has been upgraded to `v1.23.0` for submariner-operator. This entails few changes in the [submariner-operator repo](https://github.com/submariner-io/submariner-operator). Accordingly make changes in the addon as well like:

1. submariner apis are now located at `api/v1alpha1` and not `api/submariner/v1alpha1`
2. submariner operator no longer provides a `client/clientset`. Remove its usage from the addon.

Part of epic: https://github.com/submariner-io/enhancements/issues/81

**Comment by nyechiel** [comment]
This should be done with https://github.com/stolostron/submariner-addon/pull/534
