### ISSUE TITLE
Publish images using ocm-ci-image-mirror Prow workflow

### ISSUE THREAD

**Issue by dfarrell07** [stolostron/submariner-addon#490]
For robustness of image publishing, we should switch to the new ocm-ci-image-mirror Prow workflow.

Our current use of pull:

https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.6.yaml#L22

Example of push:

https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.6.yaml#L75

More info from Gurney:

> A little background: we have two different styles of image mirroring.  One is a "push" model that uses the ocm-ci-image-mirror workflow (here's an example of its use in [search-v2-api](https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.6.yaml#L75)).  This is our preferred mirror method and the only non-lossy mirroring method available.  Otherwise, we fall back on a "pull" mirroring model wherein quay-retag (the job linked above) tries to mirror the build from a floating tag in the CI registry.  Pull was the default in ACM 2.3 until ocm-ci-image-mirror was created during 2.4's development cycle.  The pull model is susceptible to timing issues and inconsistency issues between the mirrored content and the actual build.  I can go into more detail if you're curious.
It looks like [submariner-addon is still using the pull model](https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.6.yaml) (it doesn't use the ocm-ci-image-mirror workflow).  For now, we can try re-running the initial bad quay-retag run and hope that the image to mirror is t[here](https://github.com/stolostron/cicd-docs/blob/main/prow/onboarding.md#add-the-publish-job) this time.  In the longer-term, we probably want to move submariner-addon to the push model using ocm-ci-image-mirror to ensure that content is consistent and we don't hit any timing issues.  The docs on how to configure this can be found [here](https://github.com/stolostron/cicd-docs/blob/main/prow/onboarding.md#add-the-publish-job).

**Comment by dfarrell07** [comment]
I can't assign myself?

**Comment by skitt** [comment]
Tracked in https://issues.redhat.com/browse/ACM-3670
