### ISSUE TITLE
Add support for directly reachable nodes (disable NAT)

### ISSUE THREAD

**Issue by raffaelespazzoli** [stolostron/submariner-addon#82]
in some cases nodes are directly reachable via their private IPs. 
In this case it should be possible to configure disable nat: `natEnabled: false`.

**Comment by nyechiel** [comment]
@vthapar @sridhargaddam was this done already in the addon/UI?

**Comment by sridhargaddam** [comment]
> @vthapar @sridhargaddam was this done already in the addon/UI?

Yes @nyechiel the UI now supports Enable/Disable NAT. 
On a side note, with the auto-nat discovery now working fine, this flag is less relevant now.

**Comment by nyechiel** [comment]
> > @vthapar @sridhargaddam was this done already in the addon/UI?
> 
> Yes @nyechiel the UI now supports Enable/Disable NAT. On a side note, with the auto-nat discovery now working fine, this flag is less relevant now.

Yes, that's what I was thinking about. Thanks for confirming - moving to Done.
