### ISSUE TITLE
Support Load-Balancer mode when deploying Submariner

### ISSUE THREAD

**Issue by sridhargaddam** [stolostron/submariner-addon#97]
**What would you like to be added:**
Submariner supports Loadbalancer mode for supporting tunnels. It can be used instead of creating external-ips and associating them to the instances.

**Why is this needed:**
This will ease the deployment process.

**Comment by nyechiel** [comment]
This is lower priority comparing to other 2.5 deliverables. Moving to the backlog for now.

**Comment by nyechiel** [comment]
This is done with https://github.com/stolostron/submariner-addon/pull/470.
